function layer = setIhlenburgParameters(noDomains)
if nargin < 1
    noDomains = 3;
end
t = 0.15; % The thickness of the sphere
R = 5; % Midsurface radius
layer{1} = struct('media', 'fluid', ...
                  'R', R+t/2, ...
                  't',   t, ...
                  'c_f', 1524, ...
                  'rho', 1000);
layer{2} = struct('media', 'solid', ...
                  'R', R-t/2, ...
                  'E', 207e9, ...
                  'nu', 0.3, ...
                  'rho', 7669);
layer{3} = struct('media', 'fluid', ...
                  'R', 0, ...
                  'c_f', 1524, ...
                  'rho', 1000);

layer = layer(1:noDomains);